# Generated by Django 5.1.4 on 2025-02-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
