# Generated by Django 5.1.3 on 2025-01-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_delete_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images/'),
        ),
    ]
