# Generated by Django 5.1.3 on 2025-02-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_event_type_event_is_featured_event_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poi_type',
            field=models.CharField(blank=True, choices=[('landmarks', 'Landmarks'), ('museums', 'Museums'), ('parks', 'Parks'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
