# Generated by Django 5.1.5 on 2025-01-25 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='tags',
            field=models.CharField(choices=[('environmental', 'Environmental'), ('road', 'Road'), ('pollution', 'Pollution'), ('wildlife_conservation', 'Wildlife Conservation'), ('climate_change', 'Climate Change'), ('waste_management', 'Waste Management'), ('health_safety', 'Health & Safety'), ('urban_development', 'Urban Development')], default='environmental', max_length=30),
        ),
    ]
