# Generated by Django 5.1.3 on 2025-01-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='article_images/')),
                ('author', models.CharField(max_length=100)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]