# Generated by Django 5.1.5 on 2025-01-28 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0004_alter_report_latitude_alter_report_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='reports.report')),
            ],
        ),
    ]
