# Generated by Django 5.1.5 on 2025-02-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyinformation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=11.1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=22.2, max_digits=9),
            preserve_default=False,
        ),
    ]
