# Generated by Django 5.1.5 on 2025-02-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyinformation', '0003_alter_companyinformation_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinformation',
            old_name='latitude',
            new_name='ne_lat',
        ),
        migrations.RenameField(
            model_name='companyinformation',
            old_name='longitude',
            new_name='ne_lon',
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='sw_lat',
            field=models.DecimalField(decimal_places=6, default=10.1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='sw_lon',
            field=models.DecimalField(decimal_places=6, default=10.1, max_digits=9),
            preserve_default=False,
        ),
    ]
