name: Frontend Test

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install  # Install dependencies for frontend

      - name: Run frontend tests
        run: |
          cd frontend
          npm test --passWithNoTests # Run frontend tests
