name: Lint, Build & Test

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install  # Install dependencies for frontend

      - name: Run ESLint for frontend
        run: |
          cd frontend
          npx eslint src --max-warnings=0  # Lint the frontend src folder

  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install  # Install dependencies for frontend

      - name: Build frontend
        run: |
          cd frontend
          npm run build  # Build the frontend

  test-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install  # Install dependencies for frontend

      - name: Run frontend tests
        run: |
          cd frontend
          npm test  # Run frontend tests
